# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
import numpy as np
import itertools

def random_matrix(dim):
    '''
    The function generates dim x dim array of integers
    between 0 and 10.
    '''
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def list_permutations(matrix):
    '''
    The function generates a list of permutations
    for the given matrix.
    '''
    return list(itertools.permutations(range(matrix)))

def calc_sign(permutations):
    '''
    The function calculates the sign for each of the permutations,
    taking into account the number of inversions.
    '''
    inversion = 0
    for index_a in range(len(permutations)):
        for index_b in range(index_a + 1, len(permutations)):
            if permutations[index_a] > permutations[index_b]:
                inversion += 1
    if inversion % 2:
        return -1
    else:
        return 1

def calc_product(matrix, permutations):
    '''
    The function calculates the product of matrix elements
    according to the specified permutation.
    '''
    product = 1
    for index in range(len(permutations)):
        product *= matrix[index][permutations[index]]
    return product

def calc_det(matrix):
    '''
    The function calculates the determinant of
    a matrix using the permutation rule.
    '''
    permutations = list_permutations(len(matrix))
    det = 0
    for element in permutations:
        sign = calc_sign(element)
        product = calc_product(matrix, element)
        det += sign * product
    return det

size = int(input('(...)Введіть довільне додатне значення для розмірності матриці: '))
matrix = random_matrix(size)

det = calc_det(matrix)
det_linalg = np.linalg.det(matrix)

print(f'Матриця:\n{matrix}')
print(f'Детермінант визначений за допомогою перестановок: {det}')
print(f'Детермінант визначений за допомогою бібліотеки NumPy: {det_linalg}')

Матриця:
[[9 7 9 5 5]
 [1 3 9 4 1]
 [8 5 4 2 2]
 [6 4 0 1 1]
 [3 9 0 5 2]]
Детермінант визначений за допомогою перестановок: -291
Детермінант визначений за допомогою бібліотеки NumPy: -291.00000000000114
